kind: Route
apiVersion: route.openshift.io/v1
metadata:
# set your user name
  name:  user6-ng
spec:
  to:
    kind: Service
# set your user name
    name:  user6-ng
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None