kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: user6-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
# set your lab user name
      app: user6-hello-world
  template:
    metadata:
      labels:
# set your lab user name
        app: user6-hello-world
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: hello-world
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
# update with the image you build in part 1
          image: 'quay.io/metal4life/mycoolimage:v1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  ...  #this will Create Volume From our ConfigMap
spec:
...  
  template:
  ...     
    spec:
      volumes:
        - name: index-html
          configMap:
            name: index.html
            defaultMode: 420
...  # This will mount our File to the Pod File system
      containers:
      ...
          volumeMounts:
          - name: index-html
            mountPath: /tmp/html # this will mount the html.index file to it application location
      ...
...