ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/metal4life/mycoolimage'
  tag: 'chart_v39'

service:
  servicePort: 8080

test: null

github:
  user: MeirBen
  token: empty-pass
  url: https://api.github.com/repos/MeirBen/app-dev-labs/issues

Probes:
  readiness:
    httpGet:
      path: '/health/readiness'
      port: 8080
      scheme: 'HTTP'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    httpGet:
      path: '/health/liveliness'
      port: 8080
      scheme: 'HTTP'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
    
volume:
  - name: 'index-html'
    mount:
      path: '/tmp/html'