ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/metal4life/mycoolimage'
  tag: 'chart_v31'
  

service:
  servicePort: 8080

Probes:
  readiness:
    httpGet:
      path: '/health/readiness'
      schema: 'HTTP'
      port: 8080
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    httpGet:
      path: '/health/liveliness'
      schema: 'HTTP'
      port: 8080
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
    
volume:
  - name: 'index-html'
    mount:
      path: '/tmp/html'