ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/metal4life/mycoolimage'
  tag: 'chart_v19'
  

service:
  servicePort: 8080

Probes:
  readiness:
    httpGet:
      path: "/health/readiness"
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    httpGet:
      path: "/health/liveliness"
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
    
volumeMounts:
  - name: "index-html"
    mount:
      path: "/tmp/html" # Current mountPath from your deployment